modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Kamefrede/memeloadscreen"

[[mods]]
modId="memeloadscreen"
displayName="Jojo Meme Loadscreen"
version="2.0.0.0"
authors="Kamefrede"
description='''
issa joke
'''
[[dependencies.psi]]
    modId="forge"
    mandatory=true
    versionRange="[28.1.0,)"
    ordering="AFTER"
    side="BOTH"